AllCops:
  Excludes:
    - vendor/**/**
    - bin/**
    - spec/support/helpers.rb
    # tddium
    - db/**
    - config/boot.rb
    - rgloader/loader.rb
    - !ruby/regexp /.*tddium.*\.rb$/

LineLength:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

MethodLength:
  Max: 15
