AllCops:
  Exclude:
    - vendor/**/**
    - bin/**
    - spec/support/helpers.rb

LineLength:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

MethodLength:
  Max: 15

CyclomaticComplexity:
  Enabled: false
